CREATE SCHEMA IF NOT EXISTS MeetupSystemDB;
USE MeetupSystemDB;

CREATE TABLE IF NOT EXISTS Meetups 
(Id INTEGER AUTO_INCREMENT PRIMARY KEY, 
Start DATETIME NOT NULL, 
Location VARCHAR(150) NOT NULL, 
Topic VARCHAR(150) NOT NULL, 
Description VARCHAR(1000) NOT NULL);

CREATE TABLE IF NOT EXISTS Users 
(Id INTEGER AUTO_INCREMENT PRIMARY KEY, 
Name VARCHAR(100) NOT NULL, 
Birthdate DATE NOT NULL, 
Introduction VARCHAR(500), 
Avatar VARCHAR(1000),
Email VARCHAR(150) UNIQUE);

CREATE TABLE IF NOT EXISTS Statuses 
(Id INTEGER AUTO_INCREMENT PRIMARY KEY, 
Value VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS MeetupRegistration
(Id INTEGER AUTO_INCREMENT PRIMARY KEY, 
StatusId INTEGER NOT NULL, CONSTRAINT FOREIGN KEY (StatusId) REFERENCES Statuses(Id),
Meetup INTEGER NOT NULL, CONSTRAINT FOREIGN KEY (Meetup) REFERENCES Meetups(Id),
UserId INTEGER NOT NULL, CONSTRAINT FOREIGN KEY (UserId) REFERENCES Users(Id));